version: '3.9'

services:
  ovpn:
    image: kylemanna/openvpn
    restart: always
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    cap_add:
      - NET_ADMIN
    volumes:
      - data:/etc/openvpn
    ports:
      - "8083:1194/udp"


volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: $PWD/data
      o: bind    
